# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x04\x64\x61ta\x1a\x1bgoogle/protobuf/empty.proto\"+\n\tUserScore\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\"\x14\n\x12LeaderboardRequest\"6\n\x13LeaderboardResponse\x12\x1f\n\x06scores\x18\x01 \x03(\x0b\x32\x0f.data.UserScore2\x8d\x01\n\nScoreboard\x12\x36\n\tSendScore\x12\x0f.data.UserScore\x1a\x16.google.protobuf.Empty\"\x00\x12G\n\x0eGetLeaderboard\x12\x18.data.LeaderboardRequest\x1a\x19.data.LeaderboardResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERSCORE._serialized_start=49
  _USERSCORE._serialized_end=92
  _LEADERBOARDREQUEST._serialized_start=94
  _LEADERBOARDREQUEST._serialized_end=114
  _LEADERBOARDRESPONSE._serialized_start=116
  _LEADERBOARDRESPONSE._serialized_end=170
  _SCOREBOARD._serialized_start=173
  _SCOREBOARD._serialized_end=314
# @@protoc_insertion_point(module_scope)
