# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_pb2 as data__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ScoreboardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendScore = channel.unary_unary(
                '/data.Scoreboard/SendScore',
                request_serializer=data__pb2.UserScore.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetLeaderboard = channel.unary_unary(
                '/data.Scoreboard/GetLeaderboard',
                request_serializer=data__pb2.LeaderboardRequest.SerializeToString,
                response_deserializer=data__pb2.LeaderboardResponse.FromString,
                )


class ScoreboardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeaderboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScoreboardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendScore': grpc.unary_unary_rpc_method_handler(
                    servicer.SendScore,
                    request_deserializer=data__pb2.UserScore.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetLeaderboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeaderboard,
                    request_deserializer=data__pb2.LeaderboardRequest.FromString,
                    response_serializer=data__pb2.LeaderboardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data.Scoreboard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Scoreboard(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data.Scoreboard/SendScore',
            data__pb2.UserScore.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLeaderboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data.Scoreboard/GetLeaderboard',
            data__pb2.LeaderboardRequest.SerializeToString,
            data__pb2.LeaderboardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
