// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package be.cloud;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .be.cloud.Person people = 1;</code>
   */
  java.util.List<be.cloud.Person> 
      getPeopleList();
  /**
   * <code>repeated .be.cloud.Person people = 1;</code>
   */
  be.cloud.Person getPeople(int index);
  /**
   * <code>repeated .be.cloud.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .be.cloud.Person people = 1;</code>
   */
  java.util.List<? extends be.cloud.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .be.cloud.Person people = 1;</code>
   */
  be.cloud.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
