// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScoreService.proto

package com.example;

public final class ScoreServiceOuterClass {
  private ScoreServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.Score)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string player1_name = 1;</code>
     * @return The player1Name.
     */
    java.lang.String getPlayer1Name();
    /**
     * <code>string player1_name = 1;</code>
     * @return The bytes for player1Name.
     */
    com.google.protobuf.ByteString
        getPlayer1NameBytes();

    /**
     * <code>string player1_uuid = 2;</code>
     * @return The player1Uuid.
     */
    java.lang.String getPlayer1Uuid();
    /**
     * <code>string player1_uuid = 2;</code>
     * @return The bytes for player1Uuid.
     */
    com.google.protobuf.ByteString
        getPlayer1UuidBytes();

    /**
     * <code>int32 player1_score = 3;</code>
     * @return The player1Score.
     */
    int getPlayer1Score();

    /**
     * <code>string player2_name = 4;</code>
     * @return The player2Name.
     */
    java.lang.String getPlayer2Name();
    /**
     * <code>string player2_name = 4;</code>
     * @return The bytes for player2Name.
     */
    com.google.protobuf.ByteString
        getPlayer2NameBytes();

    /**
     * <code>string player2_uuid = 5;</code>
     * @return The player2Uuid.
     */
    java.lang.String getPlayer2Uuid();
    /**
     * <code>string player2_uuid = 5;</code>
     * @return The bytes for player2Uuid.
     */
    com.google.protobuf.ByteString
        getPlayer2UuidBytes();

    /**
     * <code>int32 player2_score = 6;</code>
     * @return The player2Score.
     */
    int getPlayer2Score();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 7;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 7;</code>
     * @return The timestamp.
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 7;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
  }
  /**
   * Protobuf type {@code com.example.Score}
   */
  public static final class Score extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.Score)
      ScoreOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Score.newBuilder() to construct.
    private Score(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Score() {
      player1Name_ = "";
      player1Uuid_ = "";
      player2Name_ = "";
      player2Uuid_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Score();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.ScoreServiceOuterClass.internal_static_com_example_Score_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.ScoreServiceOuterClass.internal_static_com_example_Score_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.ScoreServiceOuterClass.Score.class, com.example.ScoreServiceOuterClass.Score.Builder.class);
    }

    public static final int PLAYER1_NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object player1Name_ = "";
    /**
     * <code>string player1_name = 1;</code>
     * @return The player1Name.
     */
    @java.lang.Override
    public java.lang.String getPlayer1Name() {
      java.lang.Object ref = player1Name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        player1Name_ = s;
        return s;
      }
    }
    /**
     * <code>string player1_name = 1;</code>
     * @return The bytes for player1Name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayer1NameBytes() {
      java.lang.Object ref = player1Name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        player1Name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYER1_UUID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object player1Uuid_ = "";
    /**
     * <code>string player1_uuid = 2;</code>
     * @return The player1Uuid.
     */
    @java.lang.Override
    public java.lang.String getPlayer1Uuid() {
      java.lang.Object ref = player1Uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        player1Uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string player1_uuid = 2;</code>
     * @return The bytes for player1Uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayer1UuidBytes() {
      java.lang.Object ref = player1Uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        player1Uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYER1_SCORE_FIELD_NUMBER = 3;
    private int player1Score_ = 0;
    /**
     * <code>int32 player1_score = 3;</code>
     * @return The player1Score.
     */
    @java.lang.Override
    public int getPlayer1Score() {
      return player1Score_;
    }

    public static final int PLAYER2_NAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object player2Name_ = "";
    /**
     * <code>string player2_name = 4;</code>
     * @return The player2Name.
     */
    @java.lang.Override
    public java.lang.String getPlayer2Name() {
      java.lang.Object ref = player2Name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        player2Name_ = s;
        return s;
      }
    }
    /**
     * <code>string player2_name = 4;</code>
     * @return The bytes for player2Name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayer2NameBytes() {
      java.lang.Object ref = player2Name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        player2Name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYER2_UUID_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object player2Uuid_ = "";
    /**
     * <code>string player2_uuid = 5;</code>
     * @return The player2Uuid.
     */
    @java.lang.Override
    public java.lang.String getPlayer2Uuid() {
      java.lang.Object ref = player2Uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        player2Uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string player2_uuid = 5;</code>
     * @return The bytes for player2Uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayer2UuidBytes() {
      java.lang.Object ref = player2Uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        player2Uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYER2_SCORE_FIELD_NUMBER = 6;
    private int player2Score_ = 0;
    /**
     * <code>int32 player2_score = 6;</code>
     * @return The player2Score.
     */
    @java.lang.Override
    public int getPlayer2Score() {
      return player2Score_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 7;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 7;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(player1Name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, player1Name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(player1Uuid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, player1Uuid_);
      }
      if (player1Score_ != 0) {
        output.writeInt32(3, player1Score_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(player2Name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, player2Name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(player2Uuid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, player2Uuid_);
      }
      if (player2Score_ != 0) {
        output.writeInt32(6, player2Score_);
      }
      if (timestamp_ != null) {
        output.writeMessage(7, getTimestamp());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(player1Name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, player1Name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(player1Uuid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, player1Uuid_);
      }
      if (player1Score_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, player1Score_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(player2Name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, player2Name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(player2Uuid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, player2Uuid_);
      }
      if (player2Score_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, player2Score_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getTimestamp());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.ScoreServiceOuterClass.Score)) {
        return super.equals(obj);
      }
      com.example.ScoreServiceOuterClass.Score other = (com.example.ScoreServiceOuterClass.Score) obj;

      if (!getPlayer1Name()
          .equals(other.getPlayer1Name())) return false;
      if (!getPlayer1Uuid()
          .equals(other.getPlayer1Uuid())) return false;
      if (getPlayer1Score()
          != other.getPlayer1Score()) return false;
      if (!getPlayer2Name()
          .equals(other.getPlayer2Name())) return false;
      if (!getPlayer2Uuid()
          .equals(other.getPlayer2Uuid())) return false;
      if (getPlayer2Score()
          != other.getPlayer2Score()) return false;
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYER1_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPlayer1Name().hashCode();
      hash = (37 * hash) + PLAYER1_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayer1Uuid().hashCode();
      hash = (37 * hash) + PLAYER1_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + getPlayer1Score();
      hash = (37 * hash) + PLAYER2_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getPlayer2Name().hashCode();
      hash = (37 * hash) + PLAYER2_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayer2Uuid().hashCode();
      hash = (37 * hash) + PLAYER2_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + getPlayer2Score();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.ScoreServiceOuterClass.Score parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.ScoreServiceOuterClass.Score parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.ScoreServiceOuterClass.Score parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.ScoreServiceOuterClass.Score parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.ScoreServiceOuterClass.Score parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.ScoreServiceOuterClass.Score parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.ScoreServiceOuterClass.Score parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.ScoreServiceOuterClass.Score parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.ScoreServiceOuterClass.Score parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.ScoreServiceOuterClass.Score parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.ScoreServiceOuterClass.Score parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.ScoreServiceOuterClass.Score parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.ScoreServiceOuterClass.Score prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.Score}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.Score)
        com.example.ScoreServiceOuterClass.ScoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.ScoreServiceOuterClass.internal_static_com_example_Score_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.ScoreServiceOuterClass.internal_static_com_example_Score_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.ScoreServiceOuterClass.Score.class, com.example.ScoreServiceOuterClass.Score.Builder.class);
      }

      // Construct using com.example.ScoreServiceOuterClass.Score.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        player1Name_ = "";
        player1Uuid_ = "";
        player1Score_ = 0;
        player2Name_ = "";
        player2Uuid_ = "";
        player2Score_ = 0;
        timestamp_ = null;
        if (timestampBuilder_ != null) {
          timestampBuilder_.dispose();
          timestampBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.ScoreServiceOuterClass.internal_static_com_example_Score_descriptor;
      }

      @java.lang.Override
      public com.example.ScoreServiceOuterClass.Score getDefaultInstanceForType() {
        return com.example.ScoreServiceOuterClass.Score.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.ScoreServiceOuterClass.Score build() {
        com.example.ScoreServiceOuterClass.Score result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.ScoreServiceOuterClass.Score buildPartial() {
        com.example.ScoreServiceOuterClass.Score result = new com.example.ScoreServiceOuterClass.Score(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.ScoreServiceOuterClass.Score result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.player1Name_ = player1Name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.player1Uuid_ = player1Uuid_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.player1Score_ = player1Score_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.player2Name_ = player2Name_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.player2Uuid_ = player2Uuid_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.player2Score_ = player2Score_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.timestamp_ = timestampBuilder_ == null
              ? timestamp_
              : timestampBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.ScoreServiceOuterClass.Score) {
          return mergeFrom((com.example.ScoreServiceOuterClass.Score)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.ScoreServiceOuterClass.Score other) {
        if (other == com.example.ScoreServiceOuterClass.Score.getDefaultInstance()) return this;
        if (!other.getPlayer1Name().isEmpty()) {
          player1Name_ = other.player1Name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getPlayer1Uuid().isEmpty()) {
          player1Uuid_ = other.player1Uuid_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getPlayer1Score() != 0) {
          setPlayer1Score(other.getPlayer1Score());
        }
        if (!other.getPlayer2Name().isEmpty()) {
          player2Name_ = other.player2Name_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getPlayer2Uuid().isEmpty()) {
          player2Uuid_ = other.player2Uuid_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.getPlayer2Score() != 0) {
          setPlayer2Score(other.getPlayer2Score());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                player1Name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                player1Uuid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                player1Score_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                player2Name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                player2Uuid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                player2Score_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                input.readMessage(
                    getTimestampFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object player1Name_ = "";
      /**
       * <code>string player1_name = 1;</code>
       * @return The player1Name.
       */
      public java.lang.String getPlayer1Name() {
        java.lang.Object ref = player1Name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          player1Name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string player1_name = 1;</code>
       * @return The bytes for player1Name.
       */
      public com.google.protobuf.ByteString
          getPlayer1NameBytes() {
        java.lang.Object ref = player1Name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          player1Name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string player1_name = 1;</code>
       * @param value The player1Name to set.
       * @return This builder for chaining.
       */
      public Builder setPlayer1Name(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        player1Name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string player1_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayer1Name() {
        player1Name_ = getDefaultInstance().getPlayer1Name();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string player1_name = 1;</code>
       * @param value The bytes for player1Name to set.
       * @return This builder for chaining.
       */
      public Builder setPlayer1NameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        player1Name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object player1Uuid_ = "";
      /**
       * <code>string player1_uuid = 2;</code>
       * @return The player1Uuid.
       */
      public java.lang.String getPlayer1Uuid() {
        java.lang.Object ref = player1Uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          player1Uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string player1_uuid = 2;</code>
       * @return The bytes for player1Uuid.
       */
      public com.google.protobuf.ByteString
          getPlayer1UuidBytes() {
        java.lang.Object ref = player1Uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          player1Uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string player1_uuid = 2;</code>
       * @param value The player1Uuid to set.
       * @return This builder for chaining.
       */
      public Builder setPlayer1Uuid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        player1Uuid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string player1_uuid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayer1Uuid() {
        player1Uuid_ = getDefaultInstance().getPlayer1Uuid();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string player1_uuid = 2;</code>
       * @param value The bytes for player1Uuid to set.
       * @return This builder for chaining.
       */
      public Builder setPlayer1UuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        player1Uuid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int player1Score_ ;
      /**
       * <code>int32 player1_score = 3;</code>
       * @return The player1Score.
       */
      @java.lang.Override
      public int getPlayer1Score() {
        return player1Score_;
      }
      /**
       * <code>int32 player1_score = 3;</code>
       * @param value The player1Score to set.
       * @return This builder for chaining.
       */
      public Builder setPlayer1Score(int value) {
        
        player1Score_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 player1_score = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayer1Score() {
        bitField0_ = (bitField0_ & ~0x00000004);
        player1Score_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object player2Name_ = "";
      /**
       * <code>string player2_name = 4;</code>
       * @return The player2Name.
       */
      public java.lang.String getPlayer2Name() {
        java.lang.Object ref = player2Name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          player2Name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string player2_name = 4;</code>
       * @return The bytes for player2Name.
       */
      public com.google.protobuf.ByteString
          getPlayer2NameBytes() {
        java.lang.Object ref = player2Name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          player2Name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string player2_name = 4;</code>
       * @param value The player2Name to set.
       * @return This builder for chaining.
       */
      public Builder setPlayer2Name(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        player2Name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string player2_name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayer2Name() {
        player2Name_ = getDefaultInstance().getPlayer2Name();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string player2_name = 4;</code>
       * @param value The bytes for player2Name to set.
       * @return This builder for chaining.
       */
      public Builder setPlayer2NameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        player2Name_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object player2Uuid_ = "";
      /**
       * <code>string player2_uuid = 5;</code>
       * @return The player2Uuid.
       */
      public java.lang.String getPlayer2Uuid() {
        java.lang.Object ref = player2Uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          player2Uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string player2_uuid = 5;</code>
       * @return The bytes for player2Uuid.
       */
      public com.google.protobuf.ByteString
          getPlayer2UuidBytes() {
        java.lang.Object ref = player2Uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          player2Uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string player2_uuid = 5;</code>
       * @param value The player2Uuid to set.
       * @return This builder for chaining.
       */
      public Builder setPlayer2Uuid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        player2Uuid_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string player2_uuid = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayer2Uuid() {
        player2Uuid_ = getDefaultInstance().getPlayer2Uuid();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string player2_uuid = 5;</code>
       * @param value The bytes for player2Uuid to set.
       * @return This builder for chaining.
       */
      public Builder setPlayer2UuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        player2Uuid_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int player2Score_ ;
      /**
       * <code>int32 player2_score = 6;</code>
       * @return The player2Score.
       */
      @java.lang.Override
      public int getPlayer2Score() {
        return player2Score_;
      }
      /**
       * <code>int32 player2_score = 6;</code>
       * @param value The player2Score to set.
       * @return This builder for chaining.
       */
      public Builder setPlayer2Score(int value) {
        
        player2Score_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 player2_score = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayer2Score() {
        bitField0_ = (bitField0_ & ~0x00000020);
        player2Score_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 7;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 7;</code>
       * @return The timestamp.
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 7;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
        } else {
          timestampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 7;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 7;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (((bitField0_ & 0x00000040) != 0) &&
            timestamp_ != null &&
            timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getTimestampBuilder().mergeFrom(value);
          } else {
            timestamp_ = value;
          }
        } else {
          timestampBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 7;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000040);
        timestamp_ = null;
        if (timestampBuilder_ != null) {
          timestampBuilder_.dispose();
          timestampBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 7;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 7;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.Score)
    }

    // @@protoc_insertion_point(class_scope:com.example.Score)
    private static final com.example.ScoreServiceOuterClass.Score DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.ScoreServiceOuterClass.Score();
    }

    public static com.example.ScoreServiceOuterClass.Score getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Score>
        PARSER = new com.google.protobuf.AbstractParser<Score>() {
      @java.lang.Override
      public Score parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Score> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Score> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.ScoreServiceOuterClass.Score getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ScoresOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.Scores)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.example.Score scores = 1;</code>
     */
    java.util.List<com.example.ScoreServiceOuterClass.Score> 
        getScoresList();
    /**
     * <code>repeated .com.example.Score scores = 1;</code>
     */
    com.example.ScoreServiceOuterClass.Score getScores(int index);
    /**
     * <code>repeated .com.example.Score scores = 1;</code>
     */
    int getScoresCount();
    /**
     * <code>repeated .com.example.Score scores = 1;</code>
     */
    java.util.List<? extends com.example.ScoreServiceOuterClass.ScoreOrBuilder> 
        getScoresOrBuilderList();
    /**
     * <code>repeated .com.example.Score scores = 1;</code>
     */
    com.example.ScoreServiceOuterClass.ScoreOrBuilder getScoresOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.example.Scores}
   */
  public static final class Scores extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.Scores)
      ScoresOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Scores.newBuilder() to construct.
    private Scores(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Scores() {
      scores_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Scores();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.ScoreServiceOuterClass.internal_static_com_example_Scores_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.ScoreServiceOuterClass.internal_static_com_example_Scores_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.ScoreServiceOuterClass.Scores.class, com.example.ScoreServiceOuterClass.Scores.Builder.class);
    }

    public static final int SCORES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.example.ScoreServiceOuterClass.Score> scores_;
    /**
     * <code>repeated .com.example.Score scores = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.ScoreServiceOuterClass.Score> getScoresList() {
      return scores_;
    }
    /**
     * <code>repeated .com.example.Score scores = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.ScoreServiceOuterClass.ScoreOrBuilder> 
        getScoresOrBuilderList() {
      return scores_;
    }
    /**
     * <code>repeated .com.example.Score scores = 1;</code>
     */
    @java.lang.Override
    public int getScoresCount() {
      return scores_.size();
    }
    /**
     * <code>repeated .com.example.Score scores = 1;</code>
     */
    @java.lang.Override
    public com.example.ScoreServiceOuterClass.Score getScores(int index) {
      return scores_.get(index);
    }
    /**
     * <code>repeated .com.example.Score scores = 1;</code>
     */
    @java.lang.Override
    public com.example.ScoreServiceOuterClass.ScoreOrBuilder getScoresOrBuilder(
        int index) {
      return scores_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < scores_.size(); i++) {
        output.writeMessage(1, scores_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < scores_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, scores_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.ScoreServiceOuterClass.Scores)) {
        return super.equals(obj);
      }
      com.example.ScoreServiceOuterClass.Scores other = (com.example.ScoreServiceOuterClass.Scores) obj;

      if (!getScoresList()
          .equals(other.getScoresList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getScoresCount() > 0) {
        hash = (37 * hash) + SCORES_FIELD_NUMBER;
        hash = (53 * hash) + getScoresList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.ScoreServiceOuterClass.Scores parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.ScoreServiceOuterClass.Scores parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.ScoreServiceOuterClass.Scores parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.ScoreServiceOuterClass.Scores parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.ScoreServiceOuterClass.Scores parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.ScoreServiceOuterClass.Scores parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.ScoreServiceOuterClass.Scores parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.ScoreServiceOuterClass.Scores parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.ScoreServiceOuterClass.Scores parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.ScoreServiceOuterClass.Scores parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.ScoreServiceOuterClass.Scores parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.ScoreServiceOuterClass.Scores parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.ScoreServiceOuterClass.Scores prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.Scores}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.Scores)
        com.example.ScoreServiceOuterClass.ScoresOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.ScoreServiceOuterClass.internal_static_com_example_Scores_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.ScoreServiceOuterClass.internal_static_com_example_Scores_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.ScoreServiceOuterClass.Scores.class, com.example.ScoreServiceOuterClass.Scores.Builder.class);
      }

      // Construct using com.example.ScoreServiceOuterClass.Scores.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (scoresBuilder_ == null) {
          scores_ = java.util.Collections.emptyList();
        } else {
          scores_ = null;
          scoresBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.ScoreServiceOuterClass.internal_static_com_example_Scores_descriptor;
      }

      @java.lang.Override
      public com.example.ScoreServiceOuterClass.Scores getDefaultInstanceForType() {
        return com.example.ScoreServiceOuterClass.Scores.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.ScoreServiceOuterClass.Scores build() {
        com.example.ScoreServiceOuterClass.Scores result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.ScoreServiceOuterClass.Scores buildPartial() {
        com.example.ScoreServiceOuterClass.Scores result = new com.example.ScoreServiceOuterClass.Scores(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.example.ScoreServiceOuterClass.Scores result) {
        if (scoresBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            scores_ = java.util.Collections.unmodifiableList(scores_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.scores_ = scores_;
        } else {
          result.scores_ = scoresBuilder_.build();
        }
      }

      private void buildPartial0(com.example.ScoreServiceOuterClass.Scores result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.ScoreServiceOuterClass.Scores) {
          return mergeFrom((com.example.ScoreServiceOuterClass.Scores)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.ScoreServiceOuterClass.Scores other) {
        if (other == com.example.ScoreServiceOuterClass.Scores.getDefaultInstance()) return this;
        if (scoresBuilder_ == null) {
          if (!other.scores_.isEmpty()) {
            if (scores_.isEmpty()) {
              scores_ = other.scores_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureScoresIsMutable();
              scores_.addAll(other.scores_);
            }
            onChanged();
          }
        } else {
          if (!other.scores_.isEmpty()) {
            if (scoresBuilder_.isEmpty()) {
              scoresBuilder_.dispose();
              scoresBuilder_ = null;
              scores_ = other.scores_;
              bitField0_ = (bitField0_ & ~0x00000001);
              scoresBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getScoresFieldBuilder() : null;
            } else {
              scoresBuilder_.addAllMessages(other.scores_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.example.ScoreServiceOuterClass.Score m =
                    input.readMessage(
                        com.example.ScoreServiceOuterClass.Score.parser(),
                        extensionRegistry);
                if (scoresBuilder_ == null) {
                  ensureScoresIsMutable();
                  scores_.add(m);
                } else {
                  scoresBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.ScoreServiceOuterClass.Score> scores_ =
        java.util.Collections.emptyList();
      private void ensureScoresIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          scores_ = new java.util.ArrayList<com.example.ScoreServiceOuterClass.Score>(scores_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.ScoreServiceOuterClass.Score, com.example.ScoreServiceOuterClass.Score.Builder, com.example.ScoreServiceOuterClass.ScoreOrBuilder> scoresBuilder_;

      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public java.util.List<com.example.ScoreServiceOuterClass.Score> getScoresList() {
        if (scoresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(scores_);
        } else {
          return scoresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public int getScoresCount() {
        if (scoresBuilder_ == null) {
          return scores_.size();
        } else {
          return scoresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public com.example.ScoreServiceOuterClass.Score getScores(int index) {
        if (scoresBuilder_ == null) {
          return scores_.get(index);
        } else {
          return scoresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public Builder setScores(
          int index, com.example.ScoreServiceOuterClass.Score value) {
        if (scoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoresIsMutable();
          scores_.set(index, value);
          onChanged();
        } else {
          scoresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public Builder setScores(
          int index, com.example.ScoreServiceOuterClass.Score.Builder builderForValue) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.set(index, builderForValue.build());
          onChanged();
        } else {
          scoresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public Builder addScores(com.example.ScoreServiceOuterClass.Score value) {
        if (scoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoresIsMutable();
          scores_.add(value);
          onChanged();
        } else {
          scoresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public Builder addScores(
          int index, com.example.ScoreServiceOuterClass.Score value) {
        if (scoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoresIsMutable();
          scores_.add(index, value);
          onChanged();
        } else {
          scoresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public Builder addScores(
          com.example.ScoreServiceOuterClass.Score.Builder builderForValue) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.add(builderForValue.build());
          onChanged();
        } else {
          scoresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public Builder addScores(
          int index, com.example.ScoreServiceOuterClass.Score.Builder builderForValue) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.add(index, builderForValue.build());
          onChanged();
        } else {
          scoresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public Builder addAllScores(
          java.lang.Iterable<? extends com.example.ScoreServiceOuterClass.Score> values) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, scores_);
          onChanged();
        } else {
          scoresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public Builder clearScores() {
        if (scoresBuilder_ == null) {
          scores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          scoresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public Builder removeScores(int index) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.remove(index);
          onChanged();
        } else {
          scoresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public com.example.ScoreServiceOuterClass.Score.Builder getScoresBuilder(
          int index) {
        return getScoresFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public com.example.ScoreServiceOuterClass.ScoreOrBuilder getScoresOrBuilder(
          int index) {
        if (scoresBuilder_ == null) {
          return scores_.get(index);  } else {
          return scoresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public java.util.List<? extends com.example.ScoreServiceOuterClass.ScoreOrBuilder> 
           getScoresOrBuilderList() {
        if (scoresBuilder_ != null) {
          return scoresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(scores_);
        }
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public com.example.ScoreServiceOuterClass.Score.Builder addScoresBuilder() {
        return getScoresFieldBuilder().addBuilder(
            com.example.ScoreServiceOuterClass.Score.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public com.example.ScoreServiceOuterClass.Score.Builder addScoresBuilder(
          int index) {
        return getScoresFieldBuilder().addBuilder(
            index, com.example.ScoreServiceOuterClass.Score.getDefaultInstance());
      }
      /**
       * <code>repeated .com.example.Score scores = 1;</code>
       */
      public java.util.List<com.example.ScoreServiceOuterClass.Score.Builder> 
           getScoresBuilderList() {
        return getScoresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.ScoreServiceOuterClass.Score, com.example.ScoreServiceOuterClass.Score.Builder, com.example.ScoreServiceOuterClass.ScoreOrBuilder> 
          getScoresFieldBuilder() {
        if (scoresBuilder_ == null) {
          scoresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.ScoreServiceOuterClass.Score, com.example.ScoreServiceOuterClass.Score.Builder, com.example.ScoreServiceOuterClass.ScoreOrBuilder>(
                  scores_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          scores_ = null;
        }
        return scoresBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.example.Scores)
    }

    // @@protoc_insertion_point(class_scope:com.example.Scores)
    private static final com.example.ScoreServiceOuterClass.Scores DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.ScoreServiceOuterClass.Scores();
    }

    public static com.example.ScoreServiceOuterClass.Scores getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Scores>
        PARSER = new com.google.protobuf.AbstractParser<Scores>() {
      @java.lang.Override
      public Scores parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Scores> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Scores> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.ScoreServiceOuterClass.Scores getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_Score_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_Score_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_Scores_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_Scores_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ScoreService.proto\022\013com.example\032\033googl" +
      "e/protobuf/empty.proto\032\037google/protobuf/" +
      "timestamp.proto\"\274\001\n\005Score\022\024\n\014player1_nam" +
      "e\030\001 \001(\t\022\024\n\014player1_uuid\030\002 \001(\t\022\025\n\rplayer1" +
      "_score\030\003 \001(\005\022\024\n\014player2_name\030\004 \001(\t\022\024\n\014pl" +
      "ayer2_uuid\030\005 \001(\t\022\025\n\rplayer2_score\030\006 \001(\005\022" +
      "-\n\ttimestamp\030\007 \001(\0132\032.google.protobuf.Tim" +
      "estamp\",\n\006Scores\022\"\n\006scores\030\001 \003(\0132\022.com.e" +
      "xample.Score2\201\001\n\014ScoreService\0227\n\tSendSco" +
      "re\022\022.com.example.Score\032\026.google.protobuf" +
      ".Empty\0228\n\tGetScores\022\026.google.protobuf.Em" +
      "pty\032\023.com.example.Scoresb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_example_Score_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_Score_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_Score_descriptor,
        new java.lang.String[] { "Player1Name", "Player1Uuid", "Player1Score", "Player2Name", "Player2Uuid", "Player2Score", "Timestamp", });
    internal_static_com_example_Scores_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_Scores_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_Scores_descriptor,
        new java.lang.String[] { "Scores", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
